### ISSUE TITLE
[api-request-builder] There is a cache between building uri, affecting result

### ISSUE THREAD

**Issue by elkemper** [commercetools/nodejs#1267] opened 2019-04-17 13:16 UTC
### Description
If you use request builder sequently (e.g. by debugging in Node), and playing with `parse()` - sometimes result can contain keys, that are not in argument object
 
```js
const { createRequestBuilder } = require('@commercetools/api-request-builder') 
// output: undefined
let requestBuilder = createRequestBuilder({ projectKey: 'projectKey' });
// output: undefined
requestBuilder.customObjects.parse({id:'fkfk/23424'}).build()
// output: '/projectKey/custom-objects/fkfk/23424'
requestBuilder.customObjects.parse({key:'fkfk/23424'}).build()
// output: '/projectKey/custom-objects/key=fkfk/23424'
requestBuilder.customObjects.parse({}).build()
// output: '/projectKey/custom-objects/key=fkfk/23424'
requestBuilder.customObjects.parse({id:'fkfk/23424'}).build()
/*output: Error: A key for this resource has already been set. You cannot use both `byKey` and `byId`.
    at Object.byId (/some-user-proj/node_modules/@commercetools/api-request-builder/dist/commercetools-api-request-builder.cjs.js:627:30)
    at Object.setParams (/some-user-proj/node_modules/@commercetools/api-request-builder/dist/commercetools-api-request-builder.cjs.js:371:34)
    at Object.parse (/some-user-proj/node_modules/@commercetools/api-request-builder/dist/commercetools-api-request-builder.cjs.js:1109:17)*/
```
### Expected Behavior
Result of uri-building is not depend on previous builds

### Current Behavior
 Result of uri-building is depend on previous builds, and if you pass empty object in first run, and next - object with parameters - everything is ok. But if firstly you build with params, and then without - you will have wrong result.

**Comment by danrleyt** [comment] 2020-04-02 12:29
Hi, @elkemper thank you for letting us know about the issue. 
Could you please try it again with the latest version, we didn't have success trying to reproduce the scenario.

**Comment by ajimae** [comment] 2021-05-24 23:03
I can't seem to reproduce this issue as well on the latest **@commercetools/api-request-builder** version (5.6.3).

Please see the code snippet below I used in testing the behaviour.

```js
const { createRequestBuilder } = require('@commercetools/api-request-builder') 

let requestBuilder = createRequestBuilder({ projectKey: 'projectKey' });
let requestBuilder2 = createRequestBuilder({ projectKey: 'projectKey2' });

console.log(requestBuilder.customObjects.parse({ id:'fkfk/23424' }).build())
// output: /projectKey/custom-objects/fkfk/23424
console.log(requestBuilder.customObjects.parse({ key:'fkfk/23424' }).build())
// output: /projectKey/custom-objects/key=fkfk/23424
console.log(requestBuilder.customObjects.parse({}).build())
// output: /projectKey/custom-objects
console.log(requestBuilder.customObjects.parse({ id:'fkfk/23424' }).build())
// output: /projectKey/custom-objects/fkfk/23424
console.log(requestBuilder.customObjects.parse({ key:'fkfk/23424' }).build())
// output: /projectKey/custom-objects/key=fkfk/23424

```

**Comment by ashishhk** [comment] 2021-05-26 10:19
@elkemper I am closing this ticket as we couldn't reproduce the issue, can you please take a look at the previous comment and confirm if you still facing the issue.

**Closed by ashishhk** 2021-05-26 10:19 UTC
Labels: Minor, Node SDK, Type: Onboarding Task
