### ISSUE TITLE
[api-request-builder] Create new feature for price selection query parameters

### ISSUE THREAD

**Issue by emmenko** [commercetools/nodejs#39] opened 2017-01-21 09:25 UTC
There are 4 new query parameters used by the projections endpoint (and search).

http://dev.commercetools.com/http-api-projects-productProjections.html#get-productprojection-by-id
http://dev.commercetools.com/http-api-projects-products-search.html#search-productprojections

They should be put into a new separate feature (e.g. `query-price-selection`)

- `priceCurrency`
- `priceCountry` (_requires_ `priceCurrency`)
- `priceCustomerGroup` (_requires_ `priceCurrency`)
- `priceChannel` (_requires_ `priceCurrency`)

**Comment by wizzy25** [comment] 2017-07-25 10:23
Duplicate of #154

**Closed by wizzy25** 2017-07-25 10:23 UTC
